# -*- coding: utf-8 -*-
__author__ = 'LiYuanhe'

from Python_Lib.My_Lib_Stock import *

TEMP_FOLDER_PATH = get_config(open_config_file(), 'Temp_Path', r"D:\Gaussian\Temp")
if not os.path.isdir(TEMP_FOLDER_PATH):
    os.makedirs(TEMP_FOLDER_PATH,exist_ok=True)



functional_keywords_of_orca = ["HFS", "LDA", "VWN", "VWN3", "PWLDA", "BP86", "BLYP", "OLYP", "GLYP", "XLYP", "PW91", "mPWPW", "mPWLYP", "PBE", "RPBE", "REVPBE",
                               "PWP", "B1LYP", "B3LYP", "O3LYP", "X3LYP", "B1P", "B3P", "B3PW", "PW1PW", "mPW1PW", "mPW1LYP", "PBE0", "PW6B95", "BHANDHLYP",
                               "Meta-GGA", "TPSS", "TPSSh", "TPSS0", "M06L", "M06", "M062X", "B2PLYP", "RI-B2PLYP", "B2PLYP-D", "B2PLYP-D3", "RI-B2PLYP",
                               "mPW2PLYP", "mPW2PLYP-D", "mPW2PLYP-D3", "B2GP-PLYP", "B2K-PLYP", "DSD-PBEP86", "RI-DSD-PBEP86", "B2T-PLYP", "PWPB95",
                               "RI-PWPB95", "CCSD(T)", 'DLPNO-CCSD(T)', "HF-3c", 'PBEh-3c', 'wB97X-D3', "wB97M-V"]

basis_set_keywords_of_orca = ['3-21+G*', '3-21++G*', '3-21G*', '3-21+G**', '3-21++G**', '3-21G**', '3-21+G(d)', '3-21++G(d)', '3-21G(d)', '3-21+G(d,p)',
                              '3-21++G(d,p)', '3-21G(d,p)', '3-21+G(2d)', '3-21++G(2d)', '3-21G(2d)', '3-21+G(2d,2p)', '3-21++G(2d,2p)', '3-21G(2d,2p)',
                              '3-21+G(2df)', '3-21++G(2df)', '3-21G(2df)', '3-21+G(2df,2pd)', '3-21++G(2df,2pd)', '3-21G(2df,2pd)', '3-21+G(3df)',
                              '3-21++G(3df)', '3-21G(3df)', '3-21+G(3df,3pd)', '3-21++G(3df,3pd)', '3-21G(3df,3pd)', '3-21+G', '3-21++G', '3-21G', '3-21+GSP*',
                              '3-21++GSP*', '3-21GSP*', '3-21+GSP**', '3-21++GSP**', '3-21GSP**', '3-21+GSP(d)', '3-21++GSP(d)', '3-21GSP(d)', '3-21+GSP(d,p)',
                              '3-21++GSP(d,p)', '3-21GSP(d,p)', '3-21+GSP(2d)', '3-21++GSP(2d)', '3-21GSP(2d)', '3-21+GSP(2d,2p)', '3-21++GSP(2d,2p)',
                              '3-21GSP(2d,2p)', '3-21+GSP(2df)', '3-21++GSP(2df)', '3-21GSP(2df)', '3-21+GSP(2df,2pd)', '3-21++GSP(2df,2pd)',
                              '3-21GSP(2df,2pd)', '3-21+GSP(3df)', '3-21++GSP(3df)', '3-21GSP(3df)', '3-21+GSP(3df,3pd)', '3-21++GSP(3df,3pd)',
                              '3-21GSP(3df,3pd)', '3-21+GSP', '3-21++GSP', '3-21GSP', '4-22+GSP*', '4-22++GSP*', '4-22GSP*', '4-22+GSP**', '4-22++GSP**',
                              '4-22GSP**', '4-22+GSP(d)', '4-22++GSP(d)', '4-22GSP(d)', '4-22+GSP(d,p)', '4-22++GSP(d,p)', '4-22GSP(d,p)', '4-22+GSP(2d)',
                              '4-22++GSP(2d)', '4-22GSP(2d)', '4-22+GSP(2d,2p)', '4-22++GSP(2d,2p)', '4-22GSP(2d,2p)', '4-22+GSP(2df)', '4-22++GSP(2df)',
                              '4-22GSP(2df)', '4-22+GSP(2df,2pd)', '4-22++GSP(2df,2pd)', '4-22GSP(2df,2pd)', '4-22+GSP(3df)', '4-22++GSP(3df)', '4-22GSP(3df)',
                              '4-22+GSP(3df,3pd)', '4-22++GSP(3df,3pd)', '4-22GSP(3df,3pd)', '4-22+GSP', '4-22++GSP', '4-22GSP', '6-31+G*', '6-31++G*',
                              '6-31G*', '6-31+G**', '6-31++G**', '6-31G**', '6-31+G(d)', '6-31++G(d)', '6-31G(d)', '6-31+G(d,p)', '6-31++G(d,p)', '6-31G(d,p)',
                              '6-31+G(2d)', '6-31++G(2d)', '6-31G(2d)', '6-31+G(2d,2p)', '6-31++G(2d,2p)', '6-31G(2d,2p)', '6-31+G(2df)', '6-31++G(2df)',
                              '6-31G(2df)', '6-31+G(2df,2pd)', '6-31++G(2df,2pd)', '6-31G(2df,2pd)', '6-31+G(3df)', '6-31++G(3df)', '6-31G(3df)',
                              '6-31+G(3df,3pd)', '6-31++G(3df,3pd)', '6-31G(3df,3pd)', '6-31+G', '6-31++G', '6-31G', '6-311+G*', '6-311++G*', '6-311G*',
                              '6-311+G**', '6-311++G**', '6-311G**', '6-311+G(d)', '6-311++G(d)', '6-311G(d)', '6-311+G(d,p)', '6-311++G(d,p)', '6-311G(d,p)',
                              '6-311+G(2d)', '6-311++G(2d)', '6-311G(2d)', '6-311+G(2d,2p)', '6-311++G(2d,2p)', '6-311G(2d,2p)', '6-311+G(2df)',
                              '6-311++G(2df)', '6-311G(2df)', '6-311+G(2df,2pd)', '6-311++G(2df,2pd)', '6-311G(2df,2pd)', '6-311+G(3df)', '6-311++G(3df)',
                              '6-311G(3df)', '6-311+G(3df,3pd)', '6-311++G(3df,3pd)', '6-311G(3df,3pd)', '6-311+G', '6-311++G', '6-311G', "cc-pVDZ",
                              "cc-(p)VDZ", "aug-cc-pVDZ", "cc-pVTZ", "cc-(p)VTZ", "aug-cc-pVTZ", "cc-pVQZ", "aug-cc-pVQZ", "cc-pV5Z", "aug-cc-pV5Z", "cc-pV6Z",
                              "aug-cc-pV6Z", "cc-pCVDZ", "cc-pCVTZ", "cc-pCVQZ", "cc-pCV5Z", "cc-pV6Z", "aug-pCVDZ", "aug-pCVTZ", "aug-pCVQZ", "aug-pCV5Z",
                              "aug-cc-pV6Z", "DUNNING-DZP", 'DZP++', 'DZP+', 'aug-DZP', 'DZP', 'DZ(P)++', 'DZ(P)+', 'aug-DZ(P)', 'DZ(P)', 'DZ(d)++', 'DZ(d)+',
                              'aug-DZ(d)', 'DZ(d)', 'DZ(d,p)++', 'DZ(d,p)+', 'aug-DZ(d,p)', 'DZ(d,p)', 'DZ(2D)++', 'DZ(2D)+', 'aug-DZ(2D)', 'DZ(2D)',
                              'DZ(2D,2P)++', 'DZ(2D,2P)+', 'aug-DZ(2D,2P)', 'DZ(2D,2P)', 'DZ(2d)++', 'DZ(2d)+', 'aug-DZ(2d)', 'DZ(2d)', 'DZ(2d,2p)++',
                              'DZ(2d,2p)+', 'aug-DZ(2d,2p)', 'DZ(2d,2p)', 'DZ(2df)++', 'DZ(2df)+', 'aug-DZ(2df)', 'DZ(2df)', 'DZ(2df,2pd)++', 'DZ(2df,2pd)+',
                              'aug-DZ(2df,2pd)', 'DZ(2df,2pd)', 'DZPPP++', 'DZPPP+', 'aug-DZPPP', 'DZPPP', 'DZPP++', 'DZPP+', 'aug-DZPP', 'DZPP', 'DZ(PP)++',
                              'DZ(PP)+', 'aug-DZ(PP)', 'DZ(PP)', 'DZ++', 'DZ+', 'aug-DZ', 'DZ', 'VTZP++', 'VTZP+', 'aug-VTZP', 'VTZP', 'VTZ(P)++', 'VTZ(P)+',
                              'aug-VTZ(P)', 'VTZ(P)', 'VTZ(d)++', 'VTZ(d)+', 'aug-VTZ(d)', 'VTZ(d)', 'VTZ(d,p)++', 'VTZ(d,p)+', 'aug-VTZ(d,p)', 'VTZ(d,p)',
                              'VTZ(2D)++', 'VTZ(2D)+', 'aug-VTZ(2D)', 'VTZ(2D)', 'VTZ(2D,2P)++', 'VTZ(2D,2P)+', 'aug-VTZ(2D,2P)', 'VTZ(2D,2P)', 'VTZ(2d)++',
                              'VTZ(2d)+', 'aug-VTZ(2d)', 'VTZ(2d)', 'VTZ(2d,2p)++', 'VTZ(2d,2p)+', 'aug-VTZ(2d,2p)', 'VTZ(2d,2p)', 'VTZ(2df)++', 'VTZ(2df)+',
                              'aug-VTZ(2df)', 'VTZ(2df)', 'VTZ(2df,2pd)++', 'VTZ(2df,2pd)+', 'aug-VTZ(2df,2pd)', 'VTZ(2df,2pd)', 'VTZPPP++', 'VTZPPP+',
                              'aug-VTZPPP', 'VTZPPP', 'VTZPP++', 'VTZPP+', 'aug-VTZPP', 'VTZPP', 'VTZ(PP)++', 'VTZ(PP)+', 'aug-VTZ(PP)', 'VTZ(PP)', 'VTZ++',
                              'VTZ+', 'aug-VTZ', 'VTZ', 'SVP++', 'SVP+', 'aug-SVP', 'SVP', 'SV(P)++', 'SV(P)+', 'aug-SV(P)', 'SV(P)', 'SV(d)++', 'SV(d)+',
                              'aug-SV(d)', 'SV(d)', 'SV(d,p)++', 'SV(d,p)+', 'aug-SV(d,p)', 'SV(d,p)', 'SV(2D)++', 'SV(2D)+', 'aug-SV(2D)', 'SV(2D)',
                              'SV(2D,2P)++', 'SV(2D,2P)+', 'aug-SV(2D,2P)', 'SV(2D,2P)', 'SV(2d)++', 'SV(2d)+', 'aug-SV(2d)', 'SV(2d)', 'SV(2d,2p)++',
                              'SV(2d,2p)+', 'aug-SV(2d,2p)', 'SV(2d,2p)', 'SV(2df)++', 'SV(2df)+', 'aug-SV(2df)', 'SV(2df)', 'SV(2df,2pd)++', 'SV(2df,2pd)+',
                              'aug-SV(2df,2pd)', 'SV(2df,2pd)', 'SVPPP++', 'SVPPP+', 'aug-SVPPP', 'SVPPP', 'SVPP++', 'SVPP+', 'aug-SVPP', 'SVPP', 'SV(PP)++',
                              'SV(PP)+', 'aug-SV(PP)', 'SV(PP)', 'SV++', 'SV+', 'aug-SV', 'SV', 'TZVP++', 'TZVP+', 'aug-TZVP', 'TZVP', 'TZV(P)++', 'TZV(P)+',
                              'aug-TZV(P)', 'TZV(P)', 'TZV(d)++', 'TZV(d)+', 'aug-TZV(d)', 'TZV(d)', 'TZV(d,p)++', 'TZV(d,p)+', 'aug-TZV(d,p)', 'TZV(d,p)',
                              'TZV(2D)++', 'TZV(2D)+', 'aug-TZV(2D)', 'TZV(2D)', 'TZV(2D,2P)++', 'TZV(2D,2P)+', 'aug-TZV(2D,2P)', 'TZV(2D,2P)', 'TZV(2d)++',
                              'TZV(2d)+', 'aug-TZV(2d)', 'TZV(2d)', 'TZV(2d,2p)++', 'TZV(2d,2p)+', 'aug-TZV(2d,2p)', 'TZV(2d,2p)', 'TZV(2df)++', 'TZV(2df)+',
                              'aug-TZV(2df)', 'TZV(2df)', 'TZV(2df,2pd)++', 'TZV(2df,2pd)+', 'aug-TZV(2df,2pd)', 'TZV(2df,2pd)', 'TZVPPP++', 'TZVPPP+',
                              'aug-TZVPPP', 'TZVPPP', 'TZVPP++', 'TZVPP+', 'aug-TZVPP', 'TZVPP', 'TZV(PP)++', 'TZV(PP)+', 'aug-TZV(PP)', 'TZV(PP)', 'TZV++',
                              'TZV+', 'aug-TZV', 'TZV', 'QZVPP++', 'QZVPP+', 'aug-QZVPP', 'QZVPP', 'QZVP(P)++', 'QZVP(P)+', 'aug-QZVP(P)', 'QZVP(P)',
                              'QZVP(d)++', 'QZVP(d)+', 'aug-QZVP(d)', 'QZVP(d)', 'QZVP(d,p)++', 'QZVP(d,p)+', 'aug-QZVP(d,p)', 'QZVP(d,p)', 'QZVP(2D)++',
                              'QZVP(2D)+', 'aug-QZVP(2D)', 'QZVP(2D)', 'QZVP(2D,2P)++', 'QZVP(2D,2P)+', 'aug-QZVP(2D,2P)', 'QZVP(2D,2P)', 'QZVP(2d)++',
                              'QZVP(2d)+', 'aug-QZVP(2d)', 'QZVP(2d)', 'QZVP(2d,2p)++', 'QZVP(2d,2p)+', 'aug-QZVP(2d,2p)', 'QZVP(2d,2p)', 'QZVP(2df)++',
                              'QZVP(2df)+', 'aug-QZVP(2df)', 'QZVP(2df)', 'QZVP(2df,2pd)++', 'QZVP(2df,2pd)+', 'aug-QZVP(2df,2pd)', 'QZVP(2df,2pd)',
                              'QZVPPPP++', 'QZVPPPP+', 'aug-QZVPPPP', 'QZVPPPP', 'QZVPPP++', 'QZVPPP+', 'aug-QZVPPP', 'QZVPPP', 'QZVP(PP)++', 'QZVP(PP)+',
                              'aug-QZVP(PP)', 'QZVP(PP)', 'QZVP++', 'QZVP+', 'aug-QZVP', 'QZVP', 'QZVPP(-g,-f)P++', 'QZVPP(-g,-f)P+', 'aug-QZVPP(-g,-f)P',
                              'QZVPP(-g,-f)P', 'QZVPP(-g,-f)(P)++', 'QZVPP(-g,-f)(P)+', 'aug-QZVPP(-g,-f)(P)', 'QZVPP(-g,-f)(P)', 'QZVPP(-g,-f)(d)++',
                              'QZVPP(-g,-f)(d)+', 'aug-QZVPP(-g,-f)(d)', 'QZVPP(-g,-f)(d)', 'QZVPP(-g,-f)(d,p)++', 'QZVPP(-g,-f)(d,p)+',
                              'aug-QZVPP(-g,-f)(d,p)', 'QZVPP(-g,-f)(d,p)', 'QZVPP(-g,-f)(2D)++', 'QZVPP(-g,-f)(2D)+', 'aug-QZVPP(-g,-f)(2D)',
                              'QZVPP(-g,-f)(2D)', 'QZVPP(-g,-f)(2D,2P)++', 'QZVPP(-g,-f)(2D,2P)+', 'aug-QZVPP(-g,-f)(2D,2P)', 'QZVPP(-g,-f)(2D,2P)',
                              'QZVPP(-g,-f)(2d)++', 'QZVPP(-g,-f)(2d)+', 'aug-QZVPP(-g,-f)(2d)', 'QZVPP(-g,-f)(2d)', 'QZVPP(-g,-f)(2d,2p)++',
                              'QZVPP(-g,-f)(2d,2p)+', 'aug-QZVPP(-g,-f)(2d,2p)', 'QZVPP(-g,-f)(2d,2p)', 'QZVPP(-g,-f)(2df)++', 'QZVPP(-g,-f)(2df)+',
                              'aug-QZVPP(-g,-f)(2df)', 'QZVPP(-g,-f)(2df)', 'QZVPP(-g,-f)(2df,2pd)++', 'QZVPP(-g,-f)(2df,2pd)+', 'aug-QZVPP(-g,-f)(2df,2pd)',
                              'QZVPP(-g,-f)(2df,2pd)', 'QZVPP(-g,-f)PPP++', 'QZVPP(-g,-f)PPP+', 'aug-QZVPP(-g,-f)PPP', 'QZVPP(-g,-f)PPP', 'QZVPP(-g,-f)PP++',
                              'QZVPP(-g,-f)PP+', 'aug-QZVPP(-g,-f)PP', 'QZVPP(-g,-f)PP', 'QZVPP(-g,-f)(PP)++', 'QZVPP(-g,-f)(PP)+', 'aug-QZVPP(-g,-f)(PP)',
                              'QZVPP(-g,-f)(PP)', 'QZVPP(-g,-f)++', 'QZVPP(-g,-f)+', 'aug-QZVPP(-g,-f)', 'QZVPP(-g,-f)', "Def2-SV(P)", "Def2-SVP", "Def2-TZVP",
                              "Def2-TZVP(-f)", "Def2-TZVP(-df)", "Def2-TZVPP", "Def2-QZVP", "Def2-QZVPP", "Def2-QZVPP(-g,-f)", "ma-def2-SVP", "ma-def2-TZVP",
                              "ma-def2-TZVPP", "ma-def2-QZVPP", "def2-SVPD", "def2-TZVPD", "def2-TZVPPD", "def2-QZVPD", "def2-QZVPPD", "Def2-aug-TZVPP", "PC-1",
                              "PC-2", "PC-3", "PC-4", "Aug-PC-1", "Aug-PC-2", "Aug-PC-3", "Aug-PC-4", "ano-pVDZ", "ano-pVTZ", "ano-pVQZ", "ano-pV5Z",
                              "saug-ano-pVDZ", "saug-ano-pVTZ", "saug-ano-pVQZ", "aug-ano-pVDZ", "aug-ano-pVTZ", "aug-ano-pVQZ", "BNANO-DZP", "Bonn-ANO-DZP",
                              "BNANO-TZ2P", "Bonn-ANO-TZ2P", "BNANO-TZ3P", "NASA-AMES-ANO", "BAUSCHLICHER-ANO", "ROOS-ANO-DZP", "ROOS-ANO-TZP", "DGAUSS",
                              "SADLEJ-PVTZ", "EPR-II", "EPR-III", "IGLO-II", "IGLO-III", "Partridge-1,2,3", "Wachters", "cc-pVDZ-F12", "cc-pVTZ-F12",
                              "cc-pVQZ-F12", "cc-pVDZ-F12-CABS", "cc-pVTZ-F12-CABS", "cc-pVQZ-F12-CABS"]
