# Form implementation generated from reading ui file 'UI/Ask_CDA_Fragment.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ask_CDA_fragment_Dialog(object):
    def setupUi(self, Ask_CDA_fragment_Dialog):
        Ask_CDA_fragment_Dialog.setObjectName("Ask_CDA_fragment_Dialog")
        Ask_CDA_fragment_Dialog.resize(400, 96)
        self.gridLayout = QtWidgets.QGridLayout(Ask_CDA_fragment_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_23 = QtWidgets.QLabel(parent=Ask_CDA_fragment_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.CDA_Frag_1_lineEdit = QtWidgets.QLineEdit(parent=Ask_CDA_fragment_Dialog)
        self.CDA_Frag_1_lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CDA_Frag_1_lineEdit.setFont(font)
        self.CDA_Frag_1_lineEdit.setText("")
        self.CDA_Frag_1_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CDA_Frag_1_lineEdit.setObjectName("CDA_Frag_1_lineEdit")
        self.gridLayout.addWidget(self.CDA_Frag_1_lineEdit, 0, 1, 1, 1)
        self.CDA_Frag_2_lineEdit = QtWidgets.QLineEdit(parent=Ask_CDA_fragment_Dialog)
        self.CDA_Frag_2_lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CDA_Frag_2_lineEdit.setFont(font)
        self.CDA_Frag_2_lineEdit.setText("")
        self.CDA_Frag_2_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CDA_Frag_2_lineEdit.setObjectName("CDA_Frag_2_lineEdit")
        self.gridLayout.addWidget(self.CDA_Frag_2_lineEdit, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=Ask_CDA_fragment_Dialog)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.CDA_Frag_3_lineEdit = QtWidgets.QLineEdit(parent=Ask_CDA_fragment_Dialog)
        self.CDA_Frag_3_lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CDA_Frag_3_lineEdit.setFont(font)
        self.CDA_Frag_3_lineEdit.setText("")
        self.CDA_Frag_3_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CDA_Frag_3_lineEdit.setObjectName("CDA_Frag_3_lineEdit")
        self.gridLayout.addWidget(self.CDA_Frag_3_lineEdit, 1, 1, 1, 1)
        self.CDA_Frag_4_lineEdit = QtWidgets.QLineEdit(parent=Ask_CDA_fragment_Dialog)
        self.CDA_Frag_4_lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CDA_Frag_4_lineEdit.setFont(font)
        self.CDA_Frag_4_lineEdit.setText("")
        self.CDA_Frag_4_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CDA_Frag_4_lineEdit.setObjectName("CDA_Frag_4_lineEdit")
        self.gridLayout.addWidget(self.CDA_Frag_4_lineEdit, 1, 2, 1, 1)

        self.retranslateUi(Ask_CDA_fragment_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Ask_CDA_fragment_Dialog)

    def retranslateUi(self, Ask_CDA_fragment_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Ask_CDA_fragment_Dialog.setWindowTitle(_translate("Ask_CDA_fragment_Dialog", "Input CDA fragment"))
        self.label_23.setText(_translate("Ask_CDA_fragment_Dialog", "CDA Fragments:"))
        self.pushButton.setText(_translate("Ask_CDA_fragment_Dialog", "GView"))
