# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Automatic_xTB_optimizer_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Automatic_xTB_optimizer(object):
    def setupUi(self, Automatic_xTB_optimizer):
        Automatic_xTB_optimizer.setObjectName("Automatic_xTB_optimizer")
        Automatic_xTB_optimizer.resize(514, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Automatic_xTB_optimizer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Automatic_xTB_optimizer)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.clear_list_pushButton = QtWidgets.QPushButton(Automatic_xTB_optimizer)
        self.clear_list_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clear_list_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.clear_list_pushButton.setFont(font)
        self.clear_list_pushButton.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);}\n"
"QPushButton:checked {background:rgb(255, 255, 180);}")
        self.clear_list_pushButton.setCheckable(False)
        self.clear_list_pushButton.setChecked(False)
        self.clear_list_pushButton.setObjectName("clear_list_pushButton")
        self.horizontalLayout_2.addWidget(self.clear_list_pushButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.target_folders_tableWidget = QtWidgets.QTableWidget(Automatic_xTB_optimizer)
        self.target_folders_tableWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.target_folders_tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.target_folders_tableWidget.setFont(font)
        self.target_folders_tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.target_folders_tableWidget.setAcceptDrops(True)
        self.target_folders_tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.target_folders_tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.target_folders_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.target_folders_tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.target_folders_tableWidget.setColumnCount(2)
        self.target_folders_tableWidget.setObjectName("target_folders_tableWidget")
        self.target_folders_tableWidget.setRowCount(0)
        self.target_folders_tableWidget.horizontalHeader().setVisible(False)
        self.target_folders_tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.target_folders_tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.use_draft_folder_pushButton = QtWidgets.QPushButton(Automatic_xTB_optimizer)
        self.use_draft_folder_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.use_draft_folder_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.use_draft_folder_pushButton.setFont(font)
        self.use_draft_folder_pushButton.setToolTipDuration(0)
        self.use_draft_folder_pushButton.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);}\n"
"QPushButton:checked {background:rgb(255, 255, 180);}")
        self.use_draft_folder_pushButton.setShortcut("")
        self.use_draft_folder_pushButton.setCheckable(True)
        self.use_draft_folder_pushButton.setChecked(True)
        self.use_draft_folder_pushButton.setObjectName("use_draft_folder_pushButton")
        self.horizontalLayout.addWidget(self.use_draft_folder_pushButton)
        self.enable_pushButton = QtWidgets.QPushButton(Automatic_xTB_optimizer)
        self.enable_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.enable_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.enable_pushButton.setFont(font)
        self.enable_pushButton.setStyleSheet("QPushButton{background-color: rgb(225, 225, 225);}\n"
"QPushButton:checked {background:rgb(255, 255, 180);}")
        self.enable_pushButton.setCheckable(True)
        self.enable_pushButton.setChecked(True)
        self.enable_pushButton.setObjectName("enable_pushButton")
        self.horizontalLayout.addWidget(self.enable_pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(Automatic_xTB_optimizer)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(Automatic_xTB_optimizer)
        QtCore.QMetaObject.connectSlotsByName(Automatic_xTB_optimizer)

    def retranslateUi(self, Automatic_xTB_optimizer):
        _translate = QtCore.QCoreApplication.translate
        Automatic_xTB_optimizer.setWindowTitle(_translate("Automatic_xTB_optimizer", "Automatic xTB optimizer"))
        self.label_2.setText(_translate("Automatic_xTB_optimizer", "Monitor project folders:"))
        self.clear_list_pushButton.setText(_translate("Automatic_xTB_optimizer", " Clear list "))
        self.use_draft_folder_pushButton.setToolTip(_translate("Automatic_xTB_optimizer", "test"))
        self.use_draft_folder_pushButton.setText(_translate("Automatic_xTB_optimizer", " Use Draft Folder "))
        self.enable_pushButton.setText(_translate("Automatic_xTB_optimizer", " Enable "))
        self.label_3.setText(_translate("Automatic_xTB_optimizer", "If [Use Draft Folder] is selected, put the \"to be optimized\" gjf files in to the created xTB_opt_draft folder."))

