# Form implementation generated from reading ui file 'UI/GaussianBatchExtractButton.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GaussianBatchExtract_geom_extract(object):
    def setupUi(self, GaussianBatchExtract_geom_extract):
        GaussianBatchExtract_geom_extract.setObjectName("GaussianBatchExtract_geom_extract")
        GaussianBatchExtract_geom_extract.resize(253, 30)
        GaussianBatchExtract_geom_extract.setMaximumSize(QtCore.QSize(253, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(GaussianBatchExtract_geom_extract)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=GaussianBatchExtract_geom_extract)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.spinBox = QtWidgets.QSpinBox(parent=GaussianBatchExtract_geom_extract)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox.setMinimum(0)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.lineEdit = QtWidgets.QLineEdit(parent=GaussianBatchExtract_geom_extract)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 3)

        self.retranslateUi(GaussianBatchExtract_geom_extract)
        QtCore.QMetaObject.connectSlotsByName(GaussianBatchExtract_geom_extract)

    def retranslateUi(self, GaussianBatchExtract_geom_extract):
        _translate = QtCore.QCoreApplication.translate
        GaussianBatchExtract_geom_extract.setWindowTitle(_translate("GaussianBatchExtract_geom_extract", "Form"))
        self.pushButton.setText(_translate("GaussianBatchExtract_geom_extract", "GaussView"))
