# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/GaussianBatchCreaterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Gaussian_Batch_Creater_Form(object):
    def setupUi(self, Gaussian_Batch_Creater_Form):
        Gaussian_Batch_Creater_Form.setObjectName("Gaussian_Batch_Creater_Form")
        Gaussian_Batch_Creater_Form.resize(508, 594)
        Gaussian_Batch_Creater_Form.setAcceptDrops(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Gaussian_Batch_Creater_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Gaussian_Batch_Creater_Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.computer_spinBox = QtWidgets.QSpinBox(Gaussian_Batch_Creater_Form)
        self.computer_spinBox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.computer_spinBox.setFont(font)
        self.computer_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.computer_spinBox.setMinimum(1)
        self.computer_spinBox.setObjectName("computer_spinBox")
        self.horizontalLayout_2.addWidget(self.computer_spinBox)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Gaussian_Batch_Creater_Form)
        self.label.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.redundant_spinBox = QtWidgets.QSpinBox(Gaussian_Batch_Creater_Form)
        self.redundant_spinBox.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.redundant_spinBox.setFont(font)
        self.redundant_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.redundant_spinBox.setObjectName("redundant_spinBox")
        self.horizontalLayout_2.addWidget(self.redundant_spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.load_file_pushButton = QtWidgets.QPushButton(Gaussian_Batch_Creater_Form)
        self.load_file_pushButton.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.load_file_pushButton.setFont(font)
        self.load_file_pushButton.setObjectName("load_file_pushButton")
        self.horizontalLayout_2.addWidget(self.load_file_pushButton)
        self.save_pushButton = QtWidgets.QPushButton(Gaussian_Batch_Creater_Form)
        self.save_pushButton.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout_2.addWidget(self.save_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spontaneous_radioButton = QtWidgets.QRadioButton(Gaussian_Batch_Creater_Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.spontaneous_radioButton.setFont(font)
        self.spontaneous_radioButton.setChecked(True)
        self.spontaneous_radioButton.setObjectName("spontaneous_radioButton")
        self.horizontalLayout.addWidget(self.spontaneous_radioButton)
        self.block_first_radioButton = QtWidgets.QRadioButton(Gaussian_Batch_Creater_Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.block_first_radioButton.setFont(font)
        self.block_first_radioButton.setObjectName("block_first_radioButton")
        self.horizontalLayout.addWidget(self.block_first_radioButton)
        self.root_path_comboBox = QtWidgets.QComboBox(Gaussian_Batch_Creater_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root_path_comboBox.sizePolicy().hasHeightForWidth())
        self.root_path_comboBox.setSizePolicy(sizePolicy)
        self.root_path_comboBox.setMinimumSize(QtCore.QSize(57, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.root_path_comboBox.setFont(font)
        self.root_path_comboBox.setEditable(True)
        self.root_path_comboBox.setObjectName("root_path_comboBox")
        self.horizontalLayout.addWidget(self.root_path_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.file_list_tableWidget = QtWidgets.QTableWidget(Gaussian_Batch_Creater_Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_list_tableWidget.setFont(font)
        self.file_list_tableWidget.setAcceptDrops(True)
        self.file_list_tableWidget.setObjectName("file_list_tableWidget")
        self.file_list_tableWidget.setColumnCount(4)
        self.file_list_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_list_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_list_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_list_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_list_tableWidget.setHorizontalHeaderItem(3, item)
        self.file_list_tableWidget.horizontalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.file_list_tableWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 15)

        self.retranslateUi(Gaussian_Batch_Creater_Form)
        QtCore.QMetaObject.connectSlotsByName(Gaussian_Batch_Creater_Form)

    def retranslateUi(self, Gaussian_Batch_Creater_Form):
        _translate = QtCore.QCoreApplication.translate
        Gaussian_Batch_Creater_Form.setWindowTitle(_translate("Gaussian_Batch_Creater_Form", "Form"))
        self.label_3.setText(_translate("Gaussian_Batch_Creater_Form", "Computer:"))
        self.label.setText(_translate("Gaussian_Batch_Creater_Form", "Redundant:"))
        self.redundant_spinBox.setSuffix(_translate("Gaussian_Batch_Creater_Form", " / Cmp"))
        self.load_file_pushButton.setText(_translate("Gaussian_Batch_Creater_Form", "Load"))
        self.save_pushButton.setText(_translate("Gaussian_Batch_Creater_Form", "Save"))
        self.spontaneous_radioButton.setText(_translate("Gaussian_Batch_Creater_Form", "Spontaneous Missions"))
        self.block_first_radioButton.setText(_translate("Gaussian_Batch_Creater_Form", "Block First"))
        item = self.file_list_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Gaussian_Batch_Creater_Form", "Path"))
        item = self.file_list_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Gaussian_Batch_Creater_Form", "File Name"))
        item = self.file_list_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Gaussian_Batch_Creater_Form", "Assigned"))
        item = self.file_list_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Gaussian_Batch_Creater_Form", "Delete"))

