# Form implementation generated from reading ui file 'UI/GaussianBatchExtractFilenameInput.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GaussianBatchExtractFilenameInput(object):
    def setupUi(self, GaussianBatchExtractFilenameInput):
        GaussianBatchExtractFilenameInput.setObjectName("GaussianBatchExtractFilenameInput")
        GaussianBatchExtractFilenameInput.resize(800, 504)
        GaussianBatchExtractFilenameInput.setMaximumSize(QtCore.QSize(800, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(GaussianBatchExtractFilenameInput)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=GaussianBatchExtractFilenameInput)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=GaussianBatchExtractFilenameInput)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(parent=GaussianBatchExtractFilenameInput)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.OK_pushButton = QtWidgets.QPushButton(parent=GaussianBatchExtractFilenameInput)
        self.OK_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OK_pushButton.setFont(font)
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout.addWidget(self.OK_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(GaussianBatchExtractFilenameInput)
        QtCore.QMetaObject.connectSlotsByName(GaussianBatchExtractFilenameInput)

    def retranslateUi(self, GaussianBatchExtractFilenameInput):
        _translate = QtCore.QCoreApplication.translate
        GaussianBatchExtractFilenameInput.setWindowTitle(_translate("GaussianBatchExtractFilenameInput", "Form"))
        self.label.setText(_translate("GaussianBatchExtractFilenameInput", "<html><head/><body><p>Copy files or folders here:</p><p>Accepted types: </p></body></html>"))
        self.label_2.setText(_translate("GaussianBatchExtractFilenameInput", "<html><head/><body><p>Folders</p><p>Output File (*.out *.orca *.arc *.xtb *.xtbopt_traj.xyz)</p><p>xTB Pull File (*.xtb_Pull.xyz)</p><p>MD File (*.mdcrd)</p></body></html>"))
        self.OK_pushButton.setText(_translate("GaussianBatchExtractFilenameInput", "OK"))
