# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GaussianReaderWindow.ui'
#
# Created: Thu Apr 16 19:39:16 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReaderWindow_Form(object):
    def setupUi(self, ReaderWindow_Form):
        ReaderWindow_Form.setObjectName("ReaderWindow_Form")
        ReaderWindow_Form.resize(1318, 612)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(ReaderWindow_Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Terminations_lineEdit = QtWidgets.QLabel(ReaderWindow_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminations_lineEdit.sizePolicy().hasHeightForWidth())
        self.Terminations_lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.Terminations_lineEdit.setFont(font)
        self.Terminations_lineEdit.setText("")
        self.Terminations_lineEdit.setObjectName("Terminations_lineEdit")
        self.horizontalLayout.addWidget(self.Terminations_lineEdit)
        self.OutputFile_lineEdit = QtWidgets.QLineEdit(ReaderWindow_Form)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.OutputFile_lineEdit.setFont(font)
        self.OutputFile_lineEdit.setReadOnly(True)
        self.OutputFile_lineEdit.setObjectName("OutputFile_lineEdit")
        self.horizontalLayout.addWidget(self.OutputFile_lineEdit)
        self.LocalFile_pushButton = QtWidgets.QPushButton(ReaderWindow_Form)
        self.LocalFile_pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.LocalFile_pushButton.setFont(font)
        self.LocalFile_pushButton.setCheckable(False)
        self.LocalFile_pushButton.setChecked(False)
        self.LocalFile_pushButton.setObjectName("LocalFile_pushButton")
        self.horizontalLayout.addWidget(self.LocalFile_pushButton)
        self.SMBFile_pushButton = QtWidgets.QPushButton(ReaderWindow_Form)
        self.SMBFile_pushButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.SMBFile_pushButton.setFont(font)
        self.SMBFile_pushButton.setCheckable(False)
        self.SMBFile_pushButton.setChecked(False)
        self.SMBFile_pushButton.setObjectName("SMBFile_pushButton")
        self.horizontalLayout.addWidget(self.SMBFile_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ZoomOut_pushButton = QtWidgets.QPushButton(ReaderWindow_Form)
        self.ZoomOut_pushButton.setEnabled(False)
        self.ZoomOut_pushButton.setObjectName("ZoomOut_pushButton")
        self.horizontalLayout_2.addWidget(self.ZoomOut_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Passed_Links_textEdit = QtWidgets.QTextEdit(ReaderWindow_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Passed_Links_textEdit.sizePolicy().hasHeightForWidth())
        self.Passed_Links_textEdit.setSizePolicy(sizePolicy)
        self.Passed_Links_textEdit.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.Passed_Links_textEdit.setFont(font)
        self.Passed_Links_textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Passed_Links_textEdit.setReadOnly(True)
        self.Passed_Links_textEdit.setObjectName("Passed_Links_textEdit")
        self.horizontalLayout_3.addWidget(self.Passed_Links_textEdit)
        self.FileBrowser_TextEdit = QtWidgets.QTextEdit(ReaderWindow_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileBrowser_TextEdit.sizePolicy().hasHeightForWidth())
        self.FileBrowser_TextEdit.setSizePolicy(sizePolicy)
        self.FileBrowser_TextEdit.setMinimumSize(QtCore.QSize(680, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.FileBrowser_TextEdit.setFont(font)
        self.FileBrowser_TextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FileBrowser_TextEdit.setReadOnly(True)
        self.FileBrowser_TextEdit.setObjectName("FileBrowser_TextEdit")
        self.horizontalLayout_3.addWidget(self.FileBrowser_TextEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Gibbs_Energy_Widget = QtWidgets.QTableWidget(ReaderWindow_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gibbs_Energy_Widget.sizePolicy().hasHeightForWidth())
        self.Gibbs_Energy_Widget.setSizePolicy(sizePolicy)
        self.Gibbs_Energy_Widget.setMinimumSize(QtCore.QSize(400, 192))
        self.Gibbs_Energy_Widget.setProperty("showDropIndicator", False)
        self.Gibbs_Energy_Widget.setDragEnabled(False)
        self.Gibbs_Energy_Widget.setDragDropOverwriteMode(False)
        self.Gibbs_Energy_Widget.setRowCount(4)
        self.Gibbs_Energy_Widget.setColumnCount(0)
        self.Gibbs_Energy_Widget.setObjectName("Gibbs_Energy_Widget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.Gibbs_Energy_Widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.Gibbs_Energy_Widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.Gibbs_Energy_Widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.Gibbs_Energy_Widget.setVerticalHeaderItem(3, item)
        self.Gibbs_Energy_Widget.horizontalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.Gibbs_Energy_Widget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Calc_Route_textEdit = QtWidgets.QTextBrowser(ReaderWindow_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calc_Route_textEdit.sizePolicy().hasHeightForWidth())
        self.Calc_Route_textEdit.setSizePolicy(sizePolicy)
        self.Calc_Route_textEdit.setMinimumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Calc_Route_textEdit.setFont(font)
        self.Calc_Route_textEdit.setAcceptRichText(False)
        self.Calc_Route_textEdit.setObjectName("Calc_Route_textEdit")
        self.verticalLayout.addWidget(self.Calc_Route_textEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(ReaderWindow_Form)
        QtCore.QMetaObject.connectSlotsByName(ReaderWindow_Form)

    def retranslateUi(self, ReaderWindow_Form):
        _translate = QtCore.QCoreApplication.translate
        ReaderWindow_Form.setWindowTitle(_translate("ReaderWindow_Form", "Gaussian Reader  By. LYH"))
        self.LocalFile_pushButton.setText(_translate("ReaderWindow_Form", "Load Local"))
        self.SMBFile_pushButton.setText(_translate("ReaderWindow_Form", "Load SMB"))
        self.ZoomOut_pushButton.setText(_translate("ReaderWindow_Form", "Zoom Out"))
        item = self.Gibbs_Energy_Widget.verticalHeaderItem(0)
        item.setText(_translate("ReaderWindow_Form", "Method"))
        item = self.Gibbs_Energy_Widget.verticalHeaderItem(1)
        item.setText(_translate("ReaderWindow_Form", "H (Hartree)"))
        item = self.Gibbs_Energy_Widget.verticalHeaderItem(2)
        item.setText(_translate("ReaderWindow_Form", "S (J/mol K)"))
        item = self.Gibbs_Energy_Widget.verticalHeaderItem(3)
        item.setText(_translate("ReaderWindow_Form", "G (Hartree)"))

