# Form implementation generated from reading ui file 'UI/ssh_machines.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SSH_dialog(object):
    def setupUi(self, SSH_dialog):
        SSH_dialog.setObjectName("SSH_dialog")
        SSH_dialog.resize(504, 137)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SSH_dialog.sizePolicy().hasHeightForWidth())
        SSH_dialog.setSizePolicy(sizePolicy)
        SSH_dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(SSH_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.machines_comboBox = QtWidgets.QComboBox(parent=SSH_dialog)
        self.machines_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.machines_comboBox.setFont(font)
        self.machines_comboBox.setObjectName("machines_comboBox")
        self.verticalLayout.addWidget(self.machines_comboBox)
        self.input_lineEdit = QtWidgets.QLineEdit(parent=SSH_dialog)
        self.input_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_lineEdit.setFont(font)
        self.input_lineEdit.setText("")
        self.input_lineEdit.setObjectName("input_lineEdit")
        self.verticalLayout.addWidget(self.input_lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OK_pushButton = QtWidgets.QPushButton(parent=SSH_dialog)
        self.OK_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.OK_pushButton.setFont(font)
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout.addWidget(self.OK_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SSH_dialog)
        QtCore.QMetaObject.connectSlotsByName(SSH_dialog)

    def retranslateUi(self, SSH_dialog):
        _translate = QtCore.QCoreApplication.translate
        SSH_dialog.setWindowTitle(_translate("SSH_dialog", "SSH Pickup"))
        self.OK_pushButton.setText(_translate("SSH_dialog", "OK"))
